services:
- type: web
  name: staging-backend
  runtime: python
  rootDir: backend
  buildCommand: "pip install -r requirements.txt"
  startCommand: "uvicorn webserver:app --host 0.0.0.0 --port 8000"
  healthCheckPath: /health
  # envVars:
  #   - key: DATABASE_URL  # postgres connection
  #     fromDatabase:
  #       name: soleda-database
  #       property: connectionString

- type: web
  name: staging-frontend
  runtime: static    # possibly node
  buildCommand: "npm install && npm run build"
  rootDir: frontend
  staticPublishPath: ./dist
  routes:
  - type: rewrite
    source: /.*
    destination: /index.html

